### ISSUE TITLE
global name 'logger' is not defined

### ISSUE THREAD

**Issue by wdpless** [BreakingMalwareResearch/YetiToElastic#1]
`host@ubuntu-server:~/yeti/plugins/exports$ python
Python 2.7.16 (default, Oct  7 2019, 17:36:04)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from yeti_to_elasticsearch import YetiFeedSender
>>>
>>> sender = YetiFeedSender("yeti-feeds", excluded_feeds=("AsproxTracker"),
...     elastic_hostname="192.168.1.115",
...     elastic_port=9200)
>>> sender.extract_and_send()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "yeti_to_elasticsearch.py", line 258, in extract_and_send
    logger.error("Unknown Error: {}".format(str(e)))
NameError: global name 'logger' is not defined
`

**Comment by wdpless** [comment]
Thank you for your work on this script. I believe it will be a great use. I'm sure I'm just not doing something simple but any help would be appreciated.

**Comment by chenerlich** [comment]
Hey, thanks for your feedback.
I've updated the README and the code.
Let me know if it worked for you.
